name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./backend/

jobs:
  build:
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt
    - name: Setup the database
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        printenv
        python manage.py test
